package com.segence.kafka.connect.kafka;

import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigDef.Importance;
import org.apache.kafka.common.config.ConfigDef.Type;
import io.confluent.kafka.schemaregistry.client.SchemaRegistryClientConfig;
import io.confluent.kafka.serializers.AbstractKafkaSchemaSerDeConfig;

import org.apache.kafka.common.config.SecurityConfig;
import org.apache.kafka.common.config.SslConfigs;
import org.apache.kafka.common.config.SaslConfigs;
import org.apache.kafka.connect.runtime.WorkerConfig;

import java.util.Optional;

enum ConnectorConfigurationEntry {

    SINK_TOPIC          ("sink.topic",                                        Optional.empty(),   Type.STRING,  Optional.empty(), Importance.HIGH,   "The sink topic name."),
    KEY_CONVERTER       ("sink." + WorkerConfig.KEY_CONVERTER_CLASS_CONFIG,   Optional.empty(),   Type.CLASS,   Optional.empty(), Importance.HIGH,   WorkerConfig.KEY_CONVERTER_CLASS_DOC),
    VALUE_CONVERTER     ("sink." + WorkerConfig.VALUE_CONVERTER_CLASS_CONFIG, Optional.empty(),   Type.CLASS,   Optional.empty(), Importance.HIGH,   WorkerConfig.VALUE_CONVERTER_CLASS_DOC),
    EXACTLY_ONCE_SUPPORT("sink.exactly.once.support",                         Optional.of(false), Type.BOOLEAN, Optional.empty(), Importance.MEDIUM, "Whether to enable exactly-once support for source connectors in the cluster by using transactions to write source records and their source offsets, and by proactively fencing out old task generations before bringing up new ones."),
//
//    BOOTSTRAP_SERVER                         ("sink." + ProducerConfig.BOOTSTRAP_SERVERS_CONFIG,                        Optional.empty(),               Type.LIST,    Optional.empty(),                                            Importance.HIGH,   "A list of host/port pairs used to establish the initial connection to the Kafka cluster. Clients use this list to bootstrap and discover the full set of Kafka brokers. While the order of servers in the list does not matter, we recommend including more than one server to ensure resilience if any servers are down. This list does not need to contain the entire set of brokers, as Kafka clients automatically manage and update connections to the cluster efficiently. This list must be in the form host1:port1,host2:port2,..."),
//    CLIENT_DNS_LOOKUP                        ("sink." + ProducerConfig.CLIENT_DNS_LOOKUP_CONFIG,                        Optional.of("use_all_dns_ips"), Type.STRING,  Optional.empty(),                                            Importance.MEDIUM, "Controls how the client uses DNS lookups. If set to use_all_dns_ips, connect to each returned IP address in sequence until a successful connection is established. After a disconnection, the next IP is used. Once all IPs have been used once, the client resolves the IP(s) from the hostname again (both the JVM and the OS cache DNS name lookups, however). If set to resolve_canonical_bootstrap_servers_only, resolve each bootstrap address into a list of canonical names. After the bootstrap phase, this behaves the same as use_all_dns_ips."),
//    METADATA_MAX_AGE                         ("sink." + ProducerConfig.METADATA_MAX_AGE_CONFIG,                         Optional.of(300000L),           Type.LONG,    Optional.empty(),                                            Importance.LOW,    "The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions."),
//    METADATA_MAX_IDLE                        ("sink." + ProducerConfig.METADATA_MAX_IDLE_CONFIG,                        Optional.of(300000L),           Type.LONG,    Optional.of(ConfigDef.Range.between(5000L, Long.MAX_VALUE)), Importance.LOW,    "Controls how long the producer will cache metadata for a topic that's idle. If the elapsed time since a topic was last produced to exceeds the metadata idle duration, then the topic's metadata is forgotten and the next access to it will force a metadata fetch request."),
//    BATCH_SIZE                               ("sink." + ProducerConfig.BATCH_SIZE_CONFIG,                               Optional.of(16384),             Type.INT,     Optional.empty(),                                            Importance.MEDIUM, "The producer will attempt to batch records together into fewer requests whenever multiple records are being sent to the same partition. This helps performance on both the client and the server. This configuration controls the default batch size in bytes. <p>No attempt will be made to batch records larger than this size. <p>Requests sent to brokers will contain multiple batches, one for each partition with data available to be sent. <p>A small batch size will make batching less common and may reduce throughput (a batch size of zero will disable batching entirely). A very large batch size may use memory a bit more wastefully as we will always allocate a buffer of the specified batch size in anticipation of additional records.<p>Note: This setting gives the upper bound of the batch size to be sent. If we have fewer than this many bytes accumulated for this partition, we will 'linger' for the <code>linger.ms</code> time waiting for more records to show up. This <code>linger.ms</code> setting defaults to 0, which means we'll immediately send out a record even the accumulated batch size is under this <code>batch.size</code> setting."),
//    PARTITIONER_ADPATIVE_PARTITIONING_ENABLE ("sink." + ProducerConfig.PARTITIONER_ADPATIVE_PARTITIONING_ENABLE_CONFIG, Optional.of(true),              Type.BOOLEAN, Optional.empty(),                                            Importance.LOW,    "When set to 'true', the producer will try to adapt to broker performance and produce more messages to partitions hosted on faster brokers. If 'false', producer will try to distribute messages uniformly. Note: this setting has no effect if a custom partitioner is used"),
//    PARTITIONER_AVAILABILITY_TIMEOUT_MS      ("sink." + ProducerConfig.PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG,      Optional.of(0L),                Type.LONG,    Optional.empty(),                                            Importance.LOW,    "If a broker cannot process produce requests from a partition for <code>partitioner.availability.timeout.ms</code> time, the partitioner treats that partition as not available.  If the value is 0, this logic is disabled. Note: this setting has no effect if a custom partitioner is used or <code>partitioner.adaptive.partitioning.enable</code> is set to 'false'"),
//    PARTITIONER_IGNORE_KEYS                  ("sink." + ProducerConfig.PARTITIONER_IGNORE_KEYS_CONFIG,                  Optional.of(false),             Type.BOOLEAN, Optional.empty(),                                            Importance.MEDIUM, "When set to 'true' the producer won't use record keys to choose a partition. If 'false', producer would choose a partition based on a hash of the key when a key is present. Note: this setting has no effect if a custom partitioner is used."),
//    ACKS                                     ("sink." + ProducerConfig.ACKS_CONFIG,                                     Optional.of("all"),             Type.STRING,  Optional.empty(),                                            Importance.LOW,    "The number of acknowledgments the producer requires the leader to have received before considering a request complete. This controls the  durability of records that are sent. The following settings are allowed:  <ul> <li><code>acks=0</code> If set to zero then the producer will not wait for any acknowledgment from the server at all. The record will be immediately added to the socket buffer and considered sent. No guarantee can be made that the server has received the record in this case, and the <code>retries</code> configuration will not take effect (as the client won't generally know of any failures). The offset given back for each record will always be set to <code>-1</code>. <li><code>acks=1</code> This will mean the leader will write the record to its local log but will respond without awaiting full acknowledgement from all followers. In this case should the leader fail immediately after acknowledging the record but before the followers have replicated it then the record will be lost. <li><code>acks=all</code> This means the leader will wait for the full set of in-sync replicas to acknowledge the record. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee. This is equivalent to the acks=-1 setting.</ul><p>Note that enabling idempotence requires this config value to be 'all'. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled."),
//    LINGER_MS                                ("sink." + ProducerConfig.LINGER_MS_CONFIG,                                Optional.of(0L),                Type.LONG,    Optional.empty(),                                            Importance.MEDIUM, "The producer groups together any records that arrive in between request transmissions into a single batched request. Normally this occurs only under load when records arrive faster than they can be sent out. However in some circumstances the client may want to reduce the number of requests even under moderate load. This setting accomplishes this by adding a small amount of artificial delay&mdash;that is, rather than immediately sending out a record, the producer will wait for up to the given delay to allow other records to be sent so that the sends can be batched together. This can be thought of as analogous to Nagle's algorithm in TCP. This setting gives the upper bound on the delay for batching: once we get <code>batch.size</code> worth of records for a partition it will be sent immediately regardless of this setting, however if we have fewer than this many bytes accumulated for this partition we will 'linger' for the specified time waiting for more records to show up. This setting defaults to 0 (i.e. no delay). Setting <code>linger.ms=5</code>, for example, would have the effect of reducing the number of requests sent but would add up to 5ms of latency to records sent in the absence of load."),
//    REQUEST_TIMEOUT_MS                       ("sink." + ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG,                       Optional.of(30000),             Type.INT,     Optional.empty(),                                            Importance.MEDIUM, "The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted. This should be larger than <code>replica.lag.time.max.ms</code> (a broker configuration) to reduce the possibility of message duplication due to unnecessary producer retries."),
//    DELIVERY_TIMEOUT_MS                      ("sink." + ProducerConfig.DELIVERY_TIMEOUT_MS_CONFIG,                      Optional.of(120000),            Type.INT,     Optional.empty(),                                            Importance.MEDIUM, "An upper bound on the time to report success or failure after a call to <code>send()</code> returns. This limits the total time that a record will be delayed prior to sending, the time to await acknowledgement from the broker (if expected), and the time allowed for retriable send failures. The producer may report failure to send a record earlier than this config if either an unrecoverable error is encountered, the retries have been exhausted, or the record is added to a batch which reached an earlier delivery expiration deadline. The value of this config should be greater than or equal to the sum of <code>request.timeout.ms</code> and <code>linger.ms</code>."),
//    CLIENT_ID                                ("sink." + ProducerConfig.CLIENT_ID_CONFIG,                                Optional.empty(),               Type.STRING,  Optional.empty(),                                            Importance.LOW,    "An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging."),
//    SEND_BUFFER                              ("sink." + ProducerConfig.SEND_BUFFER_CONFIG,                              Optional.of(131072),            Type.INT,     Optional.empty(),                                            Importance.MEDIUM, "The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used."),
//    RECEIVE_BUFFER                           ("sink." + ProducerConfig.RECEIVE_BUFFER_CONFIG,                           Optional.of(32768),             Type.INT,     Optional.empty(),                                            Importance.LOW,    "The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used."),
//    MAX_REQUEST_SIZE                         ("sink." + ProducerConfig.MAX_REQUEST_SIZE_CONFIG,                         Optional.of(1048576),           Type.INT,     Optional.empty(),                                            Importance.MEDIUM, "The maximum size of a request in bytes. This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests. This is also effectively a cap on the maximum uncompressed record batch size. Note that the server has its own cap on the record batch size (after compression if compression is enabled) which may be different from this."),
//    RECONNECT_BACKOFF_MS                     ("sink." + ProducerConfig.RECONNECT_BACKOFF_MS_CONFIG,                     Optional.of(50L),               Type.LONG,    Optional.empty(),                                            Importance.LOW,    "The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker. This value is the initial backoff value and will increase exponentially for each consecutive connection failure, up to the <code>reconnect.backoff.max.ms value</code>."),
//    RECONNECT_BACKOFF_MAX_MS                 ("sink." + ProducerConfig.RECONNECT_BACKOFF_MAX_MS_CONFIG,                 Optional.of(1000L),             Type.LONG,    Optional.empty(),                                            Importance.LOW,    "The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms."),
//    MAX_BLOCK_MS                             ("sink." + ProducerConfig.MAX_BLOCK_MS_CONFIG,                             Optional.of(60000L),            Type.LONG,    Optional.empty(),                                            Importance.MEDIUM, "The configuration controls how long the <code>KafkaProducer</code>'s <code>send()</code>, <code>partitionsFor()</code>, <code>initTransactions()</code>, <code>sendOffsetsToTransaction()</code>, <code>commitTransaction()</code> and <code>abortTransaction()</code> methods will block. For <code>send()</code> this timeout bounds the total time waiting for both metadata fetch and buffer allocation (blocking in the user-supplied serializers or partitioner is not counted against this timeout). For <code>partitionsFor()</code> this timeout bounds the time spent waiting for metadata if it is unavailable. The transaction-related methods always block, but may timeout if the transaction coordinator could not be discovered or did not respond within the timeout."),
//    BUFFER_MEMORY                            ("sink." + ProducerConfig.BUFFER_MEMORY_CONFIG,                            Optional.of(33554432L),         Type.LONG,    Optional.empty(),                                            Importance.HIGH,   "The total bytes of memory the producer can use to buffer records waiting to be sent to the server. If records are sent faster than they can be delivered to the server the producer will block for <code>max.block.ms</code> after which it will throw an exception.<p>This setting should correspond roughly to the total memory the producer will use, but is not a hard bound since not all memory the producer uses is used for buffering. Some additional memory will be used for compression (if compression is enabled) as well as for maintaining in-flight requests."),
//    RETRY_BACKOFF_MS                         ("sink." + ProducerConfig.RETRY_BACKOFF_MS_CONFIG,                         Optional.of(100L),              Type.LONG,    Optional.empty(),                                            Importance.HIGH,   "The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios. This value is the initial backoff value and will increase exponentially for each failed request, up to the <code>retry.backoff.max.ms value</code>."),
//    RETRY_BACKOFF_MAX_MS                     ("sink." + ProducerConfig.RETRY_BACKOFF_MAX_MS_CONFIG,                     Optional.of(1000L),             Type.LONG,    Optional.empty(),                                            Importance.LOW,    "The maximum amount of time in milliseconds to wait when retrying a request to the broker that has repeatedly failed. If provided, the backoff per client will increase exponentially for each failed request, up to this maximum. To prevent all clients from being synchronized upon retry, a randomized jitter with a factor of 0.2 will be applied to the backoff, resulting in the backoff falling within a range between 20% below and 20% above the computed value. If <code>retry.backoff.ms</code> is set to be higher than <code>retry.backoff.max.ms</code>, then retry.backoff.max.ms will be used as a constant backoff from the beginning without any exponential increase"),
//    ENABLE_METRICS_PUSH                      ("sink." + ProducerConfig.ENABLE_METRICS_PUSH_CONFIG,                      Optional.of(true),              Type.BOOLEAN, Optional.empty(),                                            Importance.LOW,    "Whether to enable pushing of client metrics to the cluster, if the cluster has a client metrics subscription which matches this client."),
//    COMPRESSION_TYPE                         ("sink." + ProducerConfig.COMPRESSION_TYPE_CONFIG,                         Optional.of("producer"),        Type.STRING,  Optional.empty(),                                            Importance.HIGH,   "The compression type for all data generated by the producer. The default is none (i.e. no compression). Valid  values are <code>none</code>, <code>gzip</code>, <code>snappy</code>, <code>lz4</code>, or <code>zstd</code>. Compression is of full batches of data, so the efficacy of batching will also impact the compression ratio (more batching means better compression)."),
//    METRICS_SAMPLE_WINDOW_MS                 ("sink." + ProducerConfig.METRICS_SAMPLE_WINDOW_MS_CONFIG,                 Optional.of(30000L),            Type.LONG,    Optional.empty(),                                            Importance.LOW,    "The window of time a metrics sample is computed over."),
//    METRICS_NUM_SAMPLES                      ("sink." + ProducerConfig.METRICS_NUM_SAMPLES_CONFIG,                      Optional.of(2),                 Type.INT,     Optional.empty(),                                            Importance.LOW,    "The number of samples maintained to compute metrics."),
//    METRICS_RECORDING_LEVEL                  ("sink." + ProducerConfig.METRICS_RECORDING_LEVEL_CONFIG,                  Optional.of("INFO"),            Type.STRING,  Optional.empty(),                                            Importance.LOW,    "The highest recording level for metrics."),
//    METRIC_REPORTER_CLASSES                  ("sink." + ProducerConfig.METRIC_REPORTER_CLASSES_CONFIG,                  Optional.empty(),               Type.LIST,    Optional.empty(),                                            Importance.LOW,    "A list of classes to use as metrics reporters. Implementing the <code>org.apache.kafka.common.metrics.MetricsReporter</code> interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics."),
//    MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION    ("sink." + ProducerConfig.MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION,           Optional.of(5),                 Type.INT,     Optional.empty(),                                            Importance.LOW,    "The maximum number of unacknowledged requests the client will send on a single connection before blocking. Note that if this configuration is set to be greater than 1 and <code>enable.idempotence</code> is set to false, there is a risk of message reordering after a failed send due to retries (i.e., if retries are enabled);  if retries are disabled or if <code>enable.idempotence</code> is set to true, ordering will be preserved. Additionally, enabling idempotence requires the value of this configuration to be less than or equal to 5. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled."),
//    RETRIES                                  ("sink." + ProducerConfig.RETRIES_CONFIG,                                  Optional.of(0),                 Type.INT,     Optional.empty(),                                            Importance.LOW,    "Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error. Note that this retry is no different than if the client resent the record upon receiving the error. Produce requests will be failed before the number of retries has been exhausted if the timeout configured by <code>delivery.timeout.ms</code> expires first before successful acknowledgement. Users should generally prefer to leave this config unset and instead use <code>delivery.timeout.ms</code> to control retry behavior.<p>Enabling idempotence requires this config value to be greater than 0. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled.<p>Allowing retries while setting <code>enable.idempotence</code> to <code>false</code> and <code>max.in.flight.requests.per.connection</code> to greater than 1 will potentially change the ordering of records because if two batches are sent to a single partition, and the first fails and is retried but the second succeeds, then the records in the second batch may appear first."),
//    KEY_SERIALIZER_CLASS                     ("sink." + ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,                     Optional.empty(),               Type.CLASS,   Optional.empty(),                                            Importance.HIGH,   "Serializer class for key that implements the <code>org.apache.kafka.common.serialization.Serializer</code> interface."),
//    VALUE_SERIALIZER_CLASS                   ("sink." + ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,                   Optional.empty(),               Type.CLASS,   Optional.empty(),                                            Importance.HIGH,   "Serializer class for value that implements the <code>org.apache.kafka.common.serialization.Serializer</code> interface."),
//    SOCKET_CONNECTION_SETUP_TIMEOUT_MS       ("sink." + ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MS_CONFIG,       Optional.of(10000L),            Type.LONG,    Optional.empty(),                                            Importance.MEDIUM, "The amount of time the client will wait for the socket connection to be established. If the connection is not built before the timeout elapses, clients will close the socket channel. This value is the initial backoff value and will increase exponentially for each consecutive connection failure, up to the <code>socket.connection.setup.timeout.max.ms</code> value."),
//    SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS   ("sink." + ProducerConfig.SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS_CONFIG,   Optional.of(30000L),            Type.LONG,    Optional.empty(),                                            Importance.MEDIUM, "The maximum amount of time the client will wait for the socket connection to be established. The connection setup timeout will increase exponentially for each consecutive connection failure up to this maximum. To avoid connection storms, a randomization factor of 0.2 will be applied to the timeout resulting in a random range between 20% below and 20% above the computed value."),
//    CONNECTIONS_MAX_IDLE_MS                  ("sink." + ProducerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG,                  Optional.of(540000L),           Type.LONG,    Optional.empty(),                                            Importance.MEDIUM, "Close idle connections after the number of milliseconds specified by this config."),
//    PARTITIONER_CLASS                        ("sink." + ProducerConfig.PARTITIONER_CLASS_CONFIG,                        Optional.empty(),               Type.CLASS,   Optional.empty(),                                            Importance.MEDIUM, "Determines which partition to send a record to when records are produced. Available options are:<ul><li>If not set, the default partitioning logic is used. This strategy send records to a partition until at least batch.size bytes is produced to the partition. It works with the strategy:<ol><li>If no partition is specified but a key is present, choose a partition based on a hash of the key.</li><li>If no partition or key is present, choose the sticky partition that changes when at least batch.size bytes are produced to the partition.</li></ol></li><li><code>org.apache.kafka.clients.producer.RoundRobinPartitioner</code>: A partitioning strategy where each record in a series of consecutive records is sent to a different partition, regardless of whether the 'key' is provided or not, until partitions run out and the process starts over again. Note: There's a known issue that will cause uneven distribution when a new batch is created. See KAFKA-9965 for more detail.</li></ul><p>Implementing the <code>org.apache.kafka.clients.producer.Partitioner</code> interface allows you to plug in a custom partitioner."),
//    INTERCEPTOR_CLASSES                      ("sink." + ProducerConfig.INTERCEPTOR_CLASSES_CONFIG,                      Optional.empty(),               Type.LIST,    Optional.empty(),                                            Importance.LOW,    "A list of classes to use as interceptors. Implementing the <code>org.apache.kafka.clients.producer.ProducerInterceptor</code> interface allows you to intercept (and possibly mutate) the records received by the producer before they are published to the Kafka cluster. By default, there are no interceptors."),
//    ENABLE_IDEMPOTENCE                       ("sink." + ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG,                       Optional.of(true),              Type.BOOLEAN, Optional.empty(),                                            Importance.LOW,    "When set to 'true', the producer will ensure that exactly one copy of each message is written in the stream. If 'false', producer retries due to broker failures, etc., may write duplicates of the retried message in the stream. Note that enabling idempotence requires <code>max.in.flight.requests.per.connection</code> to be less than or equal to 5 (with message ordering preserved for any allowable value), <code>retries</code> to be greater than 0, and <code>acks</code> must be 'all'. <p>Idempotence is enabled by default if no conflicting configurations are set. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled. If idempotence is explicitly enabled and conflicting configurations are set, a <code>ConfigException</code> is thrown."),
//    TRANSACTION_TIMEOUT                      ("sink." + ProducerConfig.TRANSACTION_TIMEOUT_CONFIG,                      Optional.of(60000),             Type.INT,     Optional.empty(),                                            Importance.LOW,    "The maximum amount of time in milliseconds that a transaction will remain open before the coordinator proactively aborts it. The start of the transaction is set at the time that the first partition is added to it. If this value is larger than the <code>transaction.max.timeout.ms</code> setting in the broker, the request will fail with a <code>InvalidTxnTimeoutException</code> error."),
//    TRANSACTIONAL_ID                         ("sink." + ProducerConfig.TRANSACTIONAL_ID_CONFIG,                         Optional.empty(),               Type.STRING,  Optional.empty(),                                            Importance.LOW,    "The TransactionalId to use for transactional delivery. This enables reliability semantics which span multiple producer sessions since it allows the client to guarantee that transactions using the same TransactionalId have been completed prior to starting any new transactions. If no TransactionalId is provided, then the producer is limited to idempotent delivery. If a TransactionalId is configured, <code>enable.idempotence</code> is implied. By default the TransactionId is not configured, which means transactions cannot be used. Note that, by default, transactions require a cluster of at least three brokers which is the recommended setting for production; for development you can change this, by adjusting broker setting <code>transaction.state.log.replication.factor</code>."),
//
//    SSL_PROTOCOL                         ("sink." + SslConfigs.SSL_PROTOCOL_CONFIG,                          Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.MEDIUM, SslConfigs.SSL_PROTOCOL_DOC),
//    SSL_PROVIDER                         ("sink." + SslConfigs.SSL_PROVIDER_CONFIG,                          Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_PROVIDER_DOC),
//    SSL_CIPHER_SUITES                    ("sink." + SslConfigs.SSL_CIPHER_SUITES_CONFIG,                     Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_CIPHER_SUITES_DOC),
//    SSL_ENABLED_PROTOCOLS                ("sink." + SslConfigs.SSL_ENABLED_PROTOCOLS_CONFIG,                 Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_ENABLED_PROTOCOLS_DOC),
//    SSL_KEYSTORE_TYPE                    ("sink." + SslConfigs.SSL_KEYSTORE_TYPE_CONFIG,                     Optional.of(SslConfigs.DEFAULT_SSL_KEYSTORE_TYPE),                     Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYSTORE_TYPE_DOC),
//    SSL_KEYSTORE_KEY                     ("sink." + SslConfigs.SSL_KEYSTORE_KEY_CONFIG,                      Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYSTORE_KEY_DOC),
//    SSL_KEYSTORE_CERTIFICATE_CHAIN       ("sink." + SslConfigs.SSL_KEYSTORE_CERTIFICATE_CHAIN_CONFIG,        Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYSTORE_CERTIFICATE_CHAIN_DOC),
//    SSL_TRUSTSTORE_CERTIFICATES          ("sink." + SslConfigs.SSL_TRUSTSTORE_CERTIFICATES_CONFIG,           Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_TRUSTSTORE_CERTIFICATES_DOC),
//    SSL_KEYSTORE_LOCATION                ("sink." + SslConfigs.SSL_KEYSTORE_LOCATION_CONFIG,                 Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYSTORE_LOCATION_DOC),
//    SSL_KEYSTORE_PASSWORD                ("sink." + SslConfigs.SSL_KEYSTORE_PASSWORD_CONFIG,                 Optional.empty(),                                                      Type.PASSWORD, Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYSTORE_PASSWORD_DOC),
//    SSL_KEY_PASSWORD                     ("sink." + SslConfigs.SSL_KEY_PASSWORD_CONFIG,                      Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEY_PASSWORD_DOC),
//    SSL_TRUSTSTORE_TYPE                  ("sink." + SslConfigs.SSL_TRUSTSTORE_TYPE_CONFIG,                   Optional.of(SslConfigs.DEFAULT_SSL_TRUSTSTORE_TYPE),                   Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_TRUSTSTORE_TYPE_DOC),
//    SSL_TRUSTSTORE_LOCATION              ("sink." + SslConfigs.SSL_TRUSTSTORE_LOCATION_CONFIG,               Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_TRUSTSTORE_LOCATION_DOC),
//    SSL_TRUSTSTORE_PASSWORD              ("sink." + SslConfigs.SSL_TRUSTSTORE_PASSWORD_CONFIG,               Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_TRUSTSTORE_PASSWORD_DOC),
//    SSL_KEYMANAGER_ALGORITHM             ("sink." + SslConfigs.SSL_KEYMANAGER_ALGORITHM_CONFIG,              Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_KEYMANAGER_ALGORITHM_DOC),
//    SSL_TRUSTMANAGER_ALGORITHM           ("sink." + SslConfigs.SSL_TRUSTMANAGER_ALGORITHM_CONFIG,            Optional.of(SslConfigs.DEFAULT_SSL_TRUSTMANAGER_ALGORITHM),            Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_TRUSTMANAGER_ALGORITHM_DOC),
//    SSL_ENDPOINT_IDENTIFICATION_ALGORITHM("sink." + SslConfigs.SSL_ENDPOINT_IDENTIFICATION_ALGORITHM_CONFIG, Optional.of(SslConfigs.DEFAULT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM), Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_ENDPOINT_IDENTIFICATION_ALGORITHM_DOC),
//    SSL_SECURE_RANDOM_IMPLEMENTATION     ("sink." + SslConfigs.SSL_SECURE_RANDOM_IMPLEMENTATION_CONFIG,      Optional.empty(),                                                      Type.STRING,   Optional.empty(),  Importance.LOW,    SslConfigs.SSL_SECURE_RANDOM_IMPLEMENTATION_DOC),
//    SSL_ENGINE_FACTORY_CLASS             ("sink." + SslConfigs.SSL_ENGINE_FACTORY_CLASS_CONFIG,              Optional.empty(),                                                      Type.CLASS,    Optional.empty(),  Importance.LOW,    SslConfigs.SSL_ENGINE_FACTORY_CLASS_DOC),
//
//    SECURITY_PROVIDERS("sink." + SecurityConfig.SECURITY_PROVIDERS_CONFIG, Optional.empty(), Type.STRING, Optional.empty(), Importance.LOW, SecurityConfig.SECURITY_PROVIDERS_DOC),
//
//    SASL_KERBEROS_SERVICE_NAME                         ("sink." + SaslConfigs.SASL_KERBEROS_SERVICE_NAME,                          Optional.empty(),                                                                     Type.STRING,   Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_KERBEROS_SERVICE_NAME_DOC),
//    SASL_KERBEROS_KINIT_CMD                            ("sink." + SaslConfigs.SASL_KERBEROS_KINIT_CMD,                             Optional.of(SaslConfigs.DEFAULT_KERBEROS_KINIT_CMD),                                  Type.STRING,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_KERBEROS_KINIT_CMD_DOC),
//    SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR           ("sink." + SaslConfigs.SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR,            Optional.of(SaslConfigs.DEFAULT_KERBEROS_TICKET_RENEW_WINDOW_FACTOR),                 Type.DOUBLE,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR_DOC),
//    SASL_KERBEROS_TICKET_RENEW_JITTER                  ("sink." + SaslConfigs.SASL_KERBEROS_TICKET_RENEW_JITTER,                   Optional.of(SaslConfigs.DEFAULT_KERBEROS_TICKET_RENEW_JITTER),                        Type.DOUBLE,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_KERBEROS_TICKET_RENEW_JITTER_DOC),
//    SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN              ("sink." + SaslConfigs.SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN,               Optional.of(SaslConfigs.DEFAULT_KERBEROS_MIN_TIME_BEFORE_RELOGIN),                    Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN_DOC),
//    SASL_LOGIN_REFRESH_WINDOW_FACTOR                   ("sink." + SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_FACTOR,                    Optional.of(SaslConfigs.DEFAULT_LOGIN_REFRESH_WINDOW_FACTOR),                         Type.DOUBLE,   Optional.of(ConfigDef.Range.between(0.5, 1.0)),  Importance.LOW,    SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_FACTOR_DOC),
//    SASL_LOGIN_REFRESH_WINDOW_JITTER                   ("sink." + SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_JITTER,                    Optional.of(SaslConfigs.DEFAULT_LOGIN_REFRESH_WINDOW_JITTER),                         Type.DOUBLE,   Optional.of(ConfigDef.Range.between(0.0, 0.25)), Importance.LOW,    SaslConfigs.SASL_LOGIN_REFRESH_WINDOW_JITTER_DOC),
//    SASL_LOGIN_REFRESH_MIN_PERIOD_SECONDS              ("sink." + SaslConfigs.SASL_LOGIN_REFRESH_MIN_PERIOD_SECONDS,               Optional.of(SaslConfigs.DEFAULT_LOGIN_REFRESH_MIN_PERIOD_SECONDS),                    Type.SHORT,    Optional.of(ConfigDef.Range.between(0, 900)),    Importance.LOW,    SaslConfigs.SASL_LOGIN_REFRESH_MIN_PERIOD_SECONDS_DOC),
//    SASL_LOGIN_REFRESH_BUFFER_SECONDS                  ("sink." + SaslConfigs.SASL_LOGIN_REFRESH_BUFFER_SECONDS,                   Optional.of(SaslConfigs.DEFAULT_LOGIN_REFRESH_BUFFER_SECONDS),                        Type.SHORT,    Optional.of(ConfigDef.Range.between(0, 3600)),   Importance.LOW,    SaslConfigs.SASL_LOGIN_REFRESH_BUFFER_SECONDS_DOC),
//    SASL_MECHANISM                                     ("sink." + SaslConfigs.SASL_MECHANISM,                                      Optional.of(SaslConfigs.DEFAULT_SASL_MECHANISM),                                      Type.STRING,   Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_MECHANISM_DOC),
//    SASL_JAAS_CONFIG                                   ("sink." + SaslConfigs.SASL_JAAS_CONFIG,                                    Optional.empty(),                                                                     Type.PASSWORD, Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_JAAS_CONFIG_DOC),
//    SASL_CLIENT_CALLBACK_HANDLER_CLASS                 ("sink." + SaslConfigs.SASL_CLIENT_CALLBACK_HANDLER_CLASS,                  Optional.empty(),                                                                     Type.CLASS,    Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_CLIENT_CALLBACK_HANDLER_CLASS_DOC),
//    SASL_LOGIN_CALLBACK_HANDLER_CLASS                  ("sink." + SaslConfigs.SASL_LOGIN_CALLBACK_HANDLER_CLASS,                   Optional.empty(),                                                                     Type.CLASS,    Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_LOGIN_CALLBACK_HANDLER_CLASS_DOC),
//    SASL_LOGIN_CLASS                                   ("sink." + SaslConfigs.SASL_LOGIN_CLASS,                                    Optional.empty(),                                                                     Type.CLASS,    Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_LOGIN_CLASS_DOC),
//    SASL_LOGIN_CONNECT_TIMEOUT_MS                      ("sink." + SaslConfigs.SASL_LOGIN_CONNECT_TIMEOUT_MS,                       Optional.empty(),                                                                     Type.INT,      Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_LOGIN_CONNECT_TIMEOUT_MS_DOC),
//    SASL_LOGIN_READ_TIMEOUT_MS                         ("sink." + SaslConfigs.SASL_LOGIN_READ_TIMEOUT_MS,                          Optional.empty(),                                                                     Type.INT,      Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_LOGIN_READ_TIMEOUT_MS_DOC),
//    SASL_LOGIN_RETRY_BACKOFF_MAX_MS                    ("sink." + SaslConfigs.SASL_LOGIN_RETRY_BACKOFF_MAX_MS,                     Optional.of(SaslConfigs.DEFAULT_SASL_LOGIN_RETRY_BACKOFF_MAX_MS),                     Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_LOGIN_RETRY_BACKOFF_MAX_MS_DOC),
//    SASL_LOGIN_RETRY_BACKOFF_MS                        ("sink." + SaslConfigs.SASL_LOGIN_RETRY_BACKOFF_MS,                         Optional.of(SaslConfigs.DEFAULT_SASL_LOGIN_RETRY_BACKOFF_MS),                         Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_LOGIN_RETRY_BACKOFF_MS_DOC),
//    SASL_OAUTHBEARER_SCOPE_CLAIM_NAME                  ("sink." + SaslConfigs.SASL_OAUTHBEARER_SCOPE_CLAIM_NAME,                   Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_SCOPE_CLAIM_NAME),                   Type.STRING,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_SCOPE_CLAIM_NAME_DOC),
//    SASL_OAUTHBEARER_SUB_CLAIM_NAME                    ("sink." + SaslConfigs.SASL_OAUTHBEARER_SUB_CLAIM_NAME,                     Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_SUB_CLAIM_NAME),                     Type.STRING,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_SUB_CLAIM_NAME_DOC),
//    SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL                ("sink." + SaslConfigs.SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL,                 Optional.empty(),                                                                     Type.STRING,   Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL_DOC),
//    SASL_OAUTHBEARER_JWKS_ENDPOINT_URL                 ("sink." + SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_URL,                  Optional.empty(),                                                                     Type.STRING,   Optional.empty(),                                Importance.MEDIUM, SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_URL_DOC),
//    SASL_OAUTHBEARER_JWKS_ENDPOINT_REFRESH_MS          ("sink." + SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_REFRESH_MS,           Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_JWKS_ENDPOINT_REFRESH_MS),           Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_REFRESH_MS_DOC),
//    SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MAX_MS("sink." + SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MAX_MS, Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MAX_MS), Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MAX_MS_DOC),
//    SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MS    ("sink." + SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MS,     Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MS),     Type.LONG,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_JWKS_ENDPOINT_RETRY_BACKOFF_MS_DOC),
//    SASL_OAUTHBEARER_CLOCK_SKEW_SECONDS                ("sink." + SaslConfigs.SASL_OAUTHBEARER_CLOCK_SKEW_SECONDS,                 Optional.of(SaslConfigs.DEFAULT_SASL_OAUTHBEARER_CLOCK_SKEW_SECONDS),                 Type.INT,      Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_CLOCK_SKEW_SECONDS_DOC),
//    SASL_OAUTHBEARER_EXPECTED_AUDIENCE                 ("sink." + SaslConfigs.SASL_OAUTHBEARER_EXPECTED_AUDIENCE,                  Optional.empty(),                                                                     Type.LIST,     Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_EXPECTED_AUDIENCE_DOC),
//    SASL_OAUTHBEARER_EXPECTED_ISSUER                   ("sink." + SaslConfigs.SASL_OAUTHBEARER_EXPECTED_ISSUER,                    Optional.empty(),                                                                     Type.STRING,   Optional.empty(),                                Importance.LOW,    SaslConfigs.SASL_OAUTHBEARER_EXPECTED_ISSUER_DOC),
//
//    SCHEMA_REGISTRY_URL_CONFIG              ("sink." + AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG,              Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_DOC),
//    MAX_SCHEMAS_PER_SUBJECT_CONFIG          ("sink." + AbstractKafkaSchemaSerDeConfig.MAX_SCHEMAS_PER_SUBJECT_CONFIG,          Optional.of(AbstractKafkaSchemaSerDeConfig.MAX_SCHEMAS_PER_SUBJECT_DEFAULT),        Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.MAX_SCHEMAS_PER_SUBJECT_DOC),
//    NORMALIZE_SCHEMAS                       ("sink." + AbstractKafkaSchemaSerDeConfig.NORMALIZE_SCHEMAS,                       Optional.of(AbstractKafkaSchemaSerDeConfig.NORMALIZE_SCHEMAS_DEFAULT),              Type.BOOLEAN, Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.NORMALIZE_SCHEMAS_DOC),
//    AUTO_REGISTER_SCHEMAS                   ("sink." + AbstractKafkaSchemaSerDeConfig.AUTO_REGISTER_SCHEMAS,                   Optional.of(AbstractKafkaSchemaSerDeConfig.AUTO_REGISTER_SCHEMAS_DEFAULT),          Type.BOOLEAN, Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.AUTO_REGISTER_SCHEMAS_DOC),
//    USE_SCHEMA_ID                           ("sink." + AbstractKafkaSchemaSerDeConfig.USE_SCHEMA_ID,                           Optional.of(AbstractKafkaSchemaSerDeConfig.USE_SCHEMA_ID_DEFAULT),                  Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.USE_SCHEMA_ID_DOC),
//    ID_COMPATIBILITY_STRICT                 ("sink." + AbstractKafkaSchemaSerDeConfig.ID_COMPATIBILITY_STRICT,                 Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.ID_COMPATIBILITY_STRICT_DOC),
//    USE_LATEST_VERSION                      ("sink." + AbstractKafkaSchemaSerDeConfig.USE_LATEST_VERSION,                      Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.USE_LATEST_VERSION_DOC),
//    USE_LATEST_WITH_METADATA                ("sink." + AbstractKafkaSchemaSerDeConfig.USE_LATEST_WITH_METADATA,                Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.USE_LATEST_WITH_METADATA_DOC),
//    LATEST_COMPATIBILITY_STRICT             ("sink." + AbstractKafkaSchemaSerDeConfig.LATEST_COMPATIBILITY_STRICT,             Optional.of(AbstractKafkaSchemaSerDeConfig.LATEST_COMPATIBILITY_STRICT_DEFAULT),    Type.BOOLEAN, Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.LATEST_COMPATIBILITY_STRICT_DOC),
//    HTTP_CONNECT_TIMEOUT_MS                 ("sink." + AbstractKafkaSchemaSerDeConfig.HTTP_CONNECT_TIMEOUT_MS,                 Optional.of(AbstractKafkaSchemaSerDeConfig.HTTP_CONNECT_TIMEOUT_MS_DEFAULT),        Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.HTTP_CONNECT_TIMEOUT_MS_DOC),
//    HTTP_READ_TIMEOUT_MS                    ("sink." + AbstractKafkaSchemaSerDeConfig.HTTP_READ_TIMEOUT_MS,                    Optional.of(AbstractKafkaSchemaSerDeConfig.HTTP_READ_TIMEOUT_MS_DEFAULT),           Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.HTTP_READ_TIMEOUT_MS_DOC),
//    LATEST_CACHE_SIZE                       ("sink." + AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_SIZE,                       Optional.of(AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_SIZE_DEFAULT),              Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_SIZE_DOC),
//    LATEST_CACHE_TTL                        ("sink." + AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_TTL,                        Optional.of(AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_TTL_DEFAULT),               Type.INT,     Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.LATEST_CACHE_TTL_DOC),
//    SCHEMA_FORMAT                           ("sink." + AbstractKafkaSchemaSerDeConfig.SCHEMA_FORMAT,                           Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.SCHEMA_FORMAT_DOC),
//    RULE_EXECUTORS                          ("sink." + AbstractKafkaSchemaSerDeConfig.RULE_EXECUTORS,                          Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.RULE_EXECUTORS_DOCS),
//    RULE_ACTIONS                            ("sink." + AbstractKafkaSchemaSerDeConfig.RULE_ACTIONS,                            Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.RULE_ACTIONS_DOCS),
//    RULE_SERVICE_LOADER_ENABLE              ("sink." + AbstractKafkaSchemaSerDeConfig.RULE_SERVICE_LOADER_ENABLE,              Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.RULE_SERVICE_LOADER_ENABLE_DOCS),
//    BASIC_AUTH_CREDENTIALS_SOURCE           ("sink." + AbstractKafkaSchemaSerDeConfig.BASIC_AUTH_CREDENTIALS_SOURCE,           Optional.of(AbstractKafkaSchemaSerDeConfig.BASIC_AUTH_CREDENTIALS_SOURCE_DEFAULT),  Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BASIC_AUTH_CREDENTIALS_SOURCE_DOC),
//    BEARER_AUTH_CREDENTIALS_SOURCE          ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CREDENTIALS_SOURCE,          Optional.of(AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CREDENTIALS_SOURCE_DEFAULT), Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CREDENTIALS_SOURCE_DOC),
//    USER_INFO_CONFIG                        ("sink." + AbstractKafkaSchemaSerDeConfig.USER_INFO_CONFIG,                        Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_USER_INFO_DOC),
//    BEARER_AUTH_TOKEN_CONFIG                ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_TOKEN_CONFIG,                Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_TOKEN_DOC),
//    BEARER_AUTH_ISSUER_ENDPOINT_URL         ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_ISSUER_ENDPOINT_URL,         Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_ISSUER_ENDPOINT_URL_DOC),
//    BEARER_AUTH_CLIENT_ID                   ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CLIENT_ID,                   Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CLIENT_ID_DOC),
//    BEARER_AUTH_CLIENT_SECRET               ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CLIENT_SECRET,               Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CLIENT_SECRET_DOC),
//    BEARER_AUTH_SCOPE                       ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SCOPE,                       Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SCOPE_DOC),
//    BEARER_AUTH_SCOPE_CLAIM_NAME            ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SCOPE_CLAIM_NAME,            Optional.of(AbstractKafkaSchemaSerDeConfig.DEFAULT_BEARER_AUTH_SCOPE_CLAIM_NAME),   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SCOPE_CLAIM_NAME_DOC),
//    BEARER_AUTH_SUB_CLAIM_NAME              ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SUB_CLAIM_NAME,              Optional.of(AbstractKafkaSchemaSerDeConfig.DEFAULT_BEARER_AUTH_SUB_CLAIM_NAME),     Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_SUB_CLAIM_NAME_DOC),
//    BEARER_AUTH_LOGICAL_CLUSTER             ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_LOGICAL_CLUSTER,             Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_LOGICAL_CLUSTER_DOC),
//    BEARER_AUTH_IDENTITY_POOL_ID            ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_IDENTITY_POOL_ID,            Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_IDENTITY_POOL_ID_DOC),
//    BEARER_AUTH_CACHE_EXPIRY_BUFFER_SECONDS ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CACHE_EXPIRY_BUFFER_SECONDS, Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CACHE_EXPIRY_BUFFER_SECONDS_DOC),
//    BEARER_AUTH_CUSTOM_PROVIDER_CLASS       ("sink." + AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CUSTOM_PROVIDER_CLASS,       Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.BEARER_AUTH_CUSTOM_PROVIDER_CLASS_D0C),
//    CONTEXT_NAME_STRATEGY                   ("sink." + AbstractKafkaSchemaSerDeConfig.CONTEXT_NAME_STRATEGY,                   Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.CONTEXT_NAME_STRATEGY_DOC),
//    KEY_SUBJECT_NAME_STRATEGY               ("sink." + AbstractKafkaSchemaSerDeConfig.KEY_SUBJECT_NAME_STRATEGY,               Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.KEY_SUBJECT_NAME_STRATEGY_DOC),
//    VALUE_SUBJECT_NAME_STRATEGY             ("sink." + AbstractKafkaSchemaSerDeConfig.VALUE_SUBJECT_NAME_STRATEGY,             Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.VALUE_SUBJECT_NAME_STRATEGY_DOC),
//    SCHEMA_REFLECTION_CONFIG                ("sink." + AbstractKafkaSchemaSerDeConfig.SCHEMA_REFLECTION_CONFIG,                Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.SCHEMA_REFLECTION_DOC),
//    PROXY_HOST                              ("sink." + AbstractKafkaSchemaSerDeConfig.PROXY_HOST,                              Optional.empty(),                                                                   Type.STRING,  Optional.empty(), Importance.MEDIUM, AbstractKafkaSchemaSerDeConfig.PROXY_HOST_DOC),
//
//    MISSING_CACHE_SIZE        ("sink." + SchemaRegistryClientConfig.MISSING_CACHE_SIZE_CONFIG,        Optional.empty(), Type.STRING, Optional.empty(), Importance.MEDIUM, ""),
//    MISSING_ID_CACHE_TTL      ("sink." + SchemaRegistryClientConfig.MISSING_ID_CACHE_TTL_CONFIG,      Optional.empty(), Type.STRING, Optional.empty(), Importance.MEDIUM, ""),
//    MISSING_VERSION_CACHE_TTL ("sink." + SchemaRegistryClientConfig.MISSING_VERSION_CACHE_TTL_CONFIG, Optional.empty(), Type.STRING, Optional.empty(), Importance.MEDIUM, ""),
//    MISSING_SCHEMA_CACHE_TTL  ("sink." + SchemaRegistryClientConfig.MISSING_SCHEMA_CACHE_TTL_CONFIG,  Optional.empty(), Type.STRING, Optional.empty(), Importance.MEDIUM, "")
    ;

    private final String configKeyName;
    private final Optional<Object> defaultValue;
    private final Type configType;
    private final Optional<ConfigDef.Validator> validator;
    private final Importance importance;
    private final String description;

    ConnectorConfigurationEntry(String configKeyName, Optional<Object> defaultValue, Type configType, Optional<ConfigDef.Validator> validator, Importance importance, String description) {
        this.configKeyName = configKeyName;
        this.defaultValue = defaultValue;

        this.configType = configType;
        this.validator = validator;
        this.importance = importance;
        this.description = description;
    }

    public String getConfigKeyName() {
        return configKeyName;
    }

    public Optional<Object> getDefaultValue() {
        return defaultValue;
    }

    public Type getConfigType() {
        return configType;
    }

    public Optional<ConfigDef.Validator> getValidator() {
        return validator;
    }

    public Importance getImportance() {
        return importance;
    }

    public String getDescription() {
        return description;
    }
}
