name: publish
on:
  release:
    types: [published]
jobs:
  publish-to-sonatype:
    name: Publish Maven distribution 📦 to Sonatype
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - name: Publish
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: gmake publish prerelease=${{ github.event.release.prerelease }}
