name: test
on:
  push:
    branches:
    - main
    - dev
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "17" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - name: Unit testing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: make unit-test-publish-report
    - name: Integration testing
      run: make integration-test
    - name: Static Analysis
      run: make static-analysis
    # - name: Security Analysis
    #   env:
    #     NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    #   run: make security-analysis
